name: CI

on: [push]

permissions:
  contents: read

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        channel: [stable, beta]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - uses: UziTech/action-setup-atom@v3
      with:
        version: ${{ matrix.channel }}
    - name: Install dependencies
      run: apm install
    - name: Run tests
      run: atom --test spec
